//===- VTMSchedule.td - VTM Scheduling Definitions ---------*- tablegen -*-===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
// Instruction Itinerary classes used

//===----------------------------------------------------------------------===//
//

def VTMItineraries : ProcessorItineraries<
  [],
  [],
  []>;
