FIND_PATH(SYSTEMC_ROOT_DIR lib-linux64)

IF (SYSTEMC_ROOT_DIR)
  SET(SystemC_FOUND TRUE)
ENDIF (SYSTEMC_ROOT_DIR)


IF (SystemC_FOUND)
  SET(SYSTEMC ${SYSTEMC_ROOT_DIR})
  IF (NOT SystemC_FIND_QUIETLY)
    MESSAGE(STATUS "Found SystemC: ${SYSTEMC}")
  ENDIF (NOT SystemC_FIND_QUIETLY)
ELSE (SystemC_FOUND)
  IF (SystemC_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find SystemC!")
  ENDIF (SystemC_FIND_REQUIRED)
ENDIF (SystemC_FOUND)
