##===- lib/Transforms/Scalar/Makefile ----------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../../../..
LIBRARYNAME = LLVMPrepareSynthesis
LOADABLE_MODULE = 1
#BUILD_ARCHIVE = 1
BUILT_SOURCES = ../params.cpp

include $(LEVEL)/Makefile.common

