FIND_PATH(LUABIND_INCLUDE_DIR luabind.hpp)

FIND_LIBRARY(LUABIND_LIBRARY NAMES luabind)

IF (LUABIND_INCLUDE_DIR AND LUABIND_LIBRARY)
  SET(LUABIND_FOUND TRUE)
ENDIF (LUABIND_INCLUDE_DIR AND LUABIND_LIBRARY)


IF (LUABIND_FOUND)
  IF (NOT LuaBind_FIND_QUIETLY)
    MESSAGE(STATUS "Found LuaBind: ${LUABIND_LIBRARY}")
  ENDIF (NOT LuaBind_FIND_QUIETLY)
ELSE (LUABIND_FOUND)
  IF (LuaBind_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find LuaBind")
  ENDIF (LuaBind_FIND_REQUIRED)
ENDIF (LUABIND_FOUND)

