FIND_PATH(LUA_INCLUDE_DIR lua.h)

FIND_LIBRARY(LUA_LIBRARY NAMES lua)

FIND_PROGRAM(LUA_LUAC luac)
FIND_PROGRAM(LUA_BIN2C bin2c)

IF (LUA_INCLUDE_DIR AND LUA_LIBRARY AND LUA_LUAC AND LUA_BIN2C)
  SET(LUA_FOUND TRUE)
ENDIF (LUA_INCLUDE_DIR AND LUA_LIBRARY AND LUA_LUAC AND LUA_BIN2C)

IF (LUA_FOUND)
  IF (NOT Lua_FIND_QUIETLY)
    MESSAGE(STATUS "Found Lua: ${LUA_LIBRARY}")
  ENDIF (NOT Lua_FIND_QUIETLY)
ELSE (LUA_FOUND)
  IF (Lua_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Lua")
  ENDIF (Lua_FIND_REQUIRED)
ENDIF (LUA_FOUND)

