#Please note that we are using lpsolve 5.5
FIND_PATH(LPSOLVE_INCLUDE_DIR lpsolve/lp_lib.h)

FIND_LIBRARY(LPSOLVE_LIBRARY NAMES liblpsolve55)

IF (NOT LPSOLVE_INCLUDE_DIR)
  MESSAGE(FATAL_ERROR "Cannot find LPSOLVE headers!")
ENDIF (NOT LPSOLVE_INCLUDE_DIR)

IF (NOT LPSOLVE_LIBRARY)
  MESSAGE(FATAL_ERROR "Cannot find LPSOLVE libraries!")
ENDIF (NOT LPSOLVE_LIBRARY)

IF (NOT LpSolve_FIND_QUIETLY)
  MESSAGE(STATUS "Found LpSolve: ${LPSOLVE_LIBRARY}")
ENDIF (NOT LpSolve_FIND_QUIETLY)

