#Please note that we are using lua 5.1
FIND_PATH(LUA_INCLUDE_DIR lua.h)

FIND_LIBRARY(LUA_LIBRARY NAMES lua)

FIND_PROGRAM(LUA_LUAC luac)

IF (NOT LUA_INCLUDE_DIR)
  MESSAGE(FATAL_ERROR "Cannot find LUA headers!")
ENDIF (NOT LUA_INCLUDE_DIR)

IF (NOT LUA_LIBRARY)
  MESSAGE(FATAL_ERROR "Cannot find LUA libraries!")
ENDIF (NOT LUA_LIBRARY)

IF (NOT LUA_LUAC)
  MESSAGE(FATAL_ERROR "Cannot find luac!")
ENDIF (NOT LUA_LUAC)

IF (NOT Lua_FIND_QUIETLY)
  MESSAGE(STATUS "Found Lua: ${LUA_LIBRARY}")
ENDIF (NOT Lua_FIND_QUIETLY)

